title: Product owner (o algo parecido) - oferta de empleo
description: Buscamos un perfil de Product Owner con experiencia en management y scrum para incorporar a nuestro equipo
og:
  title: Product owner (o algo parecido) - oferta de empleo
  description: Buscamos un perfil de Product Owner con experiencia en management y scrum para incorporar a nuestro equipo
  type: article
  image: https://www.biko2.com/assets/images/share/share-ofertas.jpg
twitter:
  card: summary_large_image
  title: Product owner (o algo parecido) - oferta de empleo
  description: Buscamos un perfil de Product Owner con experiencia en management y scrum para incorporar a nuestro equipo
  image: https://www.biko2.com/assets/images/share/share-ofertas.jpg