title: Product owner (o algo parecido) - oferta de empleo
description: Buscamos un perfil de Product Owner con experiencia en gestión de proyectos digitales y equipos de desarrollo.
og:
  title: Product owner (o algo parecido) - oferta de empleo
  description: Buscamos un perfil de Product Owner con experiencia en gestión de proyectos digitales y equipos de desarrollo.
  type: article
  image: https://www.biko2.com/assets/images/share/share-ofertas.jpg
twitter:
  card: summary_large_image
  title: Product owner (o algo parecido) - oferta de empleo
  description: Buscamos un perfil de Product Owner con experiencia en gestión de proyectos digitales y equipos de desarrollo.
  image: https://www.biko2.com/assets/images/share/share-ofertas.jpg